server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/product/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: http://inventory-service:8083
          predicates:
            - Path=/api/inventory/**
      default-filters:
        - AddResponseHeader=X-Gateway, microservices-parent
